name: baiyangcao
markdown: kramdown

include: ["node_modules/"]
exclude: ["package.json", "README.md", "params.json"]

host: localhost

highlighter: rouge

gems: [jekyll-paginate, jekyll-sitemap]
paginate: 5