name: baiyangcao
markdown: kramdown

include: ["node_modules/"]
exclude: ["package.json", "README.md", "params.json", "stylesheets/syntax/"]

host: localhost

highlighter: rouge

gems: [jekyll-paginate]
paginate: 5